name: Main

on:
  pull_request:
  push:
    branches: [master, next]

jobs:
  build:
    name: CI
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Check size
        run: pnpm size
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          CI_BRANCH_BASE: master

      - name: Test
        run: pnpm test
        env:
          ARCHIVE_NODE_ENDPOINT: ${{ secrets.ARCHIVE_NODE_ENDPOINT }}
          VITE_PINATA_JWT: ${{ secrets.VITE_PINATA_JWT }}
          ETHERSCAN_API: ${{ secrets.ETHERSCAN_API }}

      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{matrix.os}}-node-${{ matrix.node-version }}
          base-path: 'core/evmcrispr'
          path-to-lcov: 'core/evmcrispr/coverage/lcov.info'
