name: Docs

on:
  push:
    branches: [master, next]
    paths:
      - 'packages/evmcrispr/src/**'
      - packages/evmcrispr/README.md

jobs:
  docs:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - name: Generate docs
        run: pnpm docs:evmcrispr

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
